trigger:
- main

resources:
- repo: self

variables:
  - group: variables

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: agents
    steps:
    - script: |
        /home/azdouser/tools/mgc_cli/mgc -v
        /home/azdouser/tools/mgc_cli/mgc virtual-machine instances list
      displayName: Verify MGC CLI version